/*
**
** The C code is generated by [ATS/Postiats-0-3-10]
** The starting compilation time is: 2018-1-31: 18h:38m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(ats2luapre_gt_int0_int0)
ATSdyncst_mac(ats2luapre_mul_int0_int0)
ATSdyncst_mac(fact)
ATSdyncst_mac(ats2luapre_sub_int0_int0)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
// ATSstatmpdec_void(statmp4) ;
// ATSstatmpdec_void(statmp5) ;
// ATSstatmpdec_void(statmp6) ;
// ATSstatmpdec_void(statmp7) ;
ATSstatmpdec(statmp8, atstkind_t0ype(atstype_int)) ;
// ATSstatmpdec_void(statmp9) ;
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
fact(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

/*
/home/hwxi/Research/ATS-Lua/TEST/fact.dats: 403(line=31, offs=6) -- 443(line=31, offs=46)
*/
/*
local: 
global: fact$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
fact(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 398(line=31, offs=1) -- 443(line=31, offs=46)
*/
ATSINSflab(__patsflab_fact):
/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 412(line=31, offs=15) -- 417(line=31, offs=20)
*/
ATSINSmove(tmp1, ats2luapre_gt_int0_int0(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 409(line=31, offs=12) -- 443(line=31, offs=46)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 432(line=31, offs=35) -- 435(line=31, offs=38)
*/
ATSINSmove(tmp3, ats2luapre_sub_int0_int0(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 427(line=31, offs=30) -- 436(line=31, offs=39)
*/
ATSINSmove(tmp2, fact(tmp3)) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 423(line=31, offs=26) -- 436(line=31, offs=39)
*/
ATSINSmove(tmpret0, ats2luapre_mul_int0_int0(arg0, tmp2)) ;

} ATSelse() {
/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 442(line=31, offs=45) -- 443(line=31, offs=46)
*/
ATSINSmove(tmpret0, ATSPMVi0nt(1)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [fact] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_hwxi_057_Research_057_ATS_055_Lua_057_TEST_057_fact_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_hwxi_057_Research_057_ATS_055_Lua_057_TEST_057_fact_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_hwxi_057_Research_057_ATS_055_Lua_057_TEST_057_fact_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwxi_057_Research_057_ATS_055_Lua_057_TEST_057_fact_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwxi_057_Research_057_ATS_055_Lua_057_TEST_057_fact_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 490(line=36, offs=10) -- 528(line=36, offs=48)
*/
ATSINSmove_void(statmp4, atspre_print_string(ATSPMVstring("fact("))) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 490(line=36, offs=10) -- 528(line=36, offs=48)
*/
ATSINSmove_void(statmp5, atspre_print_int(ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 490(line=36, offs=10) -- 528(line=36, offs=48)
*/
ATSINSmove_void(statmp6, atspre_print_string(ATSPMVstring(") = "))) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 520(line=36, offs=40) -- 526(line=36, offs=46)
*/
ATSINSmove(statmp8, fact(ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 490(line=36, offs=10) -- 528(line=36, offs=48)
*/
ATSINSmove_void(statmp7, atspre_print_int(statmp8)) ;

/*
emit_instr: loc0 = /home/hwxi/Research/ATS-Lua/TEST/fact.dats: 490(line=36, offs=10) -- 528(line=36, offs=48)
*/
ATSINSmove_void(statmp9, atspre_print_newline()) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
ATSextern()
atsvoid_t0ype
fact_dynload()
{
ATSfunbody_beg()
ATSINSmove_void(tmpret_void, _057_home_057_hwxi_057_Research_057_ATS_055_Lua_057_TEST_057_fact_056_dats__dynload()) ;
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} // end-of-dynload-alias

/* ****** ****** */

/* end-of-compilation-unit */
