--[[
--
-- The Lua code is generated by atscc2lua
-- The starting compilation time is: 2018-4-18: 14h: 6m
--
--]]

--[[ require libats ]]
require "libatscc2lua"

local statmp10

local statmp13

local statmp15

local statmp17

local statmp18

local statmp20

local statmp21

local statmp30

local statmp32

local statmp33

local statmp34

local statmp36

local statmp37

local statmp38

local statmp40

local statmp41

local statmp42

local statmp45

local statmp49

local statmp53

function
_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__isTriangle(arg0, arg1, arg2)

--
-- knd = 0
  local tmpret0
  local tmp1
  local tmp2
  local tmp3
  local tmp4
  local tmp5
  local tmplab, tmplab_lua
--
  -- __patsflab_isTriangle
  tmp3 = ats2luapre_add_int0_int0(arg0, arg1)
  tmp2 = ats2luapre_gt_int0_int0(tmp3, arg2)
  if(tmp2) then
    tmp4 = ats2luapre_add_int0_int0(arg0, arg2)
    tmp1 = ats2luapre_gt_int0_int0(tmp4, arg1)
   else
    tmp1 = false
  end -- end-of-if
  if(tmp1) then
    tmp5 = ats2luapre_add_int0_int0(arg1, arg2)
    tmpret0 = ats2luapre_gt_int0_int0(tmp5, arg0)
   else
    tmpret0 = false
  end -- end-of-if
  return tmpret0
end -- end-of-function


function
__patsfun_1(arg0, arg1, arg2)

--
-- knd = 1
  local apy0
  local apy1
  local apy2
  local tmpret6
  local tmp7
  local tmp8
  local tmp9
  local funlab_lua
  local tmplab, tmplab_lua
--
  while true do
    funlab_lua = 0
    -- __patsflab___patsfun_1
    tmp7 = ats2luapre_lt_int0_int0(arg0, 2)
    if(tmp7) then
      tmpret6 = arg1
     else
      tmp8 = ats2luapre_sub_int0_int0(arg0, 1)
      tmp9 = ats2luapre_add_int0_int0(arg1, arg2)
      -- ATStailcalseq_beg
      apy0 = tmp8
      apy1 = tmp9
      apy2 = arg1
      arg0 = apy0
      arg1 = apy1
      arg2 = apy2
      funlab_lua = 1 -- __patsflab___patsfun_1
      -- ATStailcalseq_end
    end -- end-of-if
    if funlab_lua <= 0 then return tmpret6  end
  end -- endwhile-fun
end -- end-of-function


function
_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__fib_trec(arg0)

--
-- knd = 0
  local tmpret11
  local tmplab, tmplab_lua
--
  -- __patsflab_fib_trec
  tmpret11 = statmp10(arg0, 1, 0)
  return tmpret11
end -- end-of-function


function
__patsfun_3(arg0)

--
-- knd = 0
  local tmpret24
  local tmp25
  local tmp26
  local tmp27
  local tmp28
  local tmp29
  local tmplab, tmplab_lua
--
  -- __patsflab___patsfun_3
  tmp25 = ats2luapre_gte_int0_int0(arg0, 2)
  if(tmp25) then
    tmp27 = ats2luapre_sub_int0_int0(arg0, 1)
    tmp26 = __patsfun_3(tmp27)
    tmp29 = ats2luapre_sub_int0_int0(arg0, 2)
    tmp28 = __patsfun_3(tmp29)
    tmpret24 = ats2luapre_add_int0_int0(tmp26, tmp28)
   else
    tmpret24 = arg0
  end -- end-of-if
  return tmpret24
end -- end-of-function

-- dynloadflag_minit
local _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__dynloadflag = 0

function
_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__dynload()

--
-- knd = 0
  local tmplab, tmplab_lua
--
  -- ATSdynload()
  -- ATSdynloadflag_sta(_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__dynloadflag(78))
  if(ATSCKiseqz(_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__dynloadflag)) then
    _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__dynloadflag = 1 -- flag is set
    statmp10 = __patsfun_1
    statmp13 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__isTriangle(3, 4, 5)
    ats2luapre_assert_errmsg_bool0(statmp13, "/home/calvin/code/ats-lua/tests/triangle/triangle.dats: 597(line=28, offs=10) -- 625(line=28, offs=38)")
    statmp15 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__isTriangle(5, 4, 3)
    ats2luapre_assert_errmsg_bool0(statmp15, "/home/calvin/code/ats-lua/tests/triangle/triangle.dats: 635(line=29, offs=10) -- 663(line=29, offs=38)")
    statmp18 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__isTriangle(1, 2, 3)
    statmp17 = ats2luapre_neg_bool0(statmp18)
    ats2luapre_assert_errmsg_bool0(statmp17, "/home/calvin/code/ats-lua/tests/triangle/triangle.dats: 673(line=30, offs=10) -- 702(line=30, offs=39)")
    statmp21 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__isTriangle(3, 2, 1)
    statmp20 = ats2luapre_neg_bool0(statmp21)
    ats2luapre_assert_errmsg_bool0(statmp20, "/home/calvin/code/ats-lua/tests/triangle/triangle.dats: 712(line=31, offs=10) -- 741(line=31, offs=39)")
    ats2luapre_print_string("Testing of [isTriangle] is done successfully!")
    ats2luapre_print_newline()
    statmp30 = __patsfun_3
    statmp33 = statmp30(5)
    statmp34 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__fib_trec(5)
    statmp32 = ats2luapre_eq_int0_int0(statmp33, statmp34)
    ats2luapre_assert_errmsg_bool0(statmp32, "/home/calvin/code/ats-lua/tests/triangle/triangle.dats: 891(line=37, offs=10) -- 922(line=37, offs=41)")
    statmp37 = statmp30(10)
    statmp38 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__fib_trec(10)
    statmp36 = ats2luapre_eq_int0_int0(statmp37, statmp38)
    ats2luapre_assert_errmsg_bool0(statmp36, "/home/calvin/code/ats-lua/tests/triangle/triangle.dats: 932(line=38, offs=10) -- 965(line=38, offs=43)")
    statmp41 = statmp30(20)
    statmp42 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__fib_trec(20)
    statmp40 = ats2luapre_eq_int0_int0(statmp41, statmp42)
    ats2luapre_assert_errmsg_bool0(statmp40, "/home/calvin/code/ats-lua/tests/triangle/triangle.dats: 975(line=39, offs=10) -- 1008(line=39, offs=43)")
    ats2luapre_print_string("fib_trec(5) = ")
    statmp45 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__fib_trec(5)
    ats2luapre_print_int(statmp45)
    ats2luapre_print_newline()
    ats2luapre_print_string("fib_trec(10) = ")
    statmp49 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__fib_trec(10)
    ats2luapre_print_int(statmp49)
    ats2luapre_print_newline()
    ats2luapre_print_string("fib_trec(20) = ")
    statmp53 = _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__fib_trec(20)
    ats2luapre_print_int(statmp53)
    ats2luapre_print_newline()
    ats2luapre_print_string("Testing of [fib_trec] is done successfully!")
    ats2luapre_print_newline()
  end -- end-of-if
  return
end -- end-of-function


function
triangle_dynload()

--
-- knd = 0
  local tmplab, tmplab_lua
--
  _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_triangle_057_triangle_056_dats__dynload()
  return
end -- end-of-function


--[[ ------ ------ ]]

--[[ end-of-compilation-unit ]]
