--[[
--
-- The Lua code is generated by atscc2lua
-- The starting compilation time is: 2018-4-25: 15h: 7m
--
--]]

--[[ require libats ]]
require "libatscc2lua"
-- dynloadflag_minit
local _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_template_057_main_056_dats__dynloadflag = 0

function
_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_template_057_main_056_dats__dynload()

--
-- knd = 0
  local tmplab, tmplab_lua
--
  -- ATSdynload()
  -- ATSdynloadflag_sta(_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_template_057_main_056_dats__dynloadflag(14))
  if(ATSCKiseqz(_057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_template_057_main_056_dats__dynloadflag)) then
    _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_template_057_main_056_dats__dynloadflag = 1 -- flag is set
    ats2luapre_print_string("Hello, world!")
    ats2luapre_print_newline()
  end -- end-of-if
  return
end -- end-of-function


function
main_dynload()

--
-- knd = 0
  local tmplab, tmplab_lua
--
  _057_home_057_calvin_057_code_057_ats_055_lua_057_tests_057_template_057_main_056_dats__dynload()
  return
end -- end-of-function


--[[ ------ ------ ]]

--[[ end-of-compilation-unit ]]
